[cnbeta_top10]
title = "cnbeta一周点击排行"
url = "https://www.cnbeta.com.tw/top10.htm"
entrySelector = ".cnbeta-update-list.rank-list.category-update.counter_news .items-area.rank-list .item"
titleSelector = "dl dt"
linkSelector = "dl dd a"
contentSelector = "dl dd p"
dateSelector = ".meta-data label.labels"
